### ISSUE TITLE
error on using api

### ISSUE THREAD

**Issue by hamedisu** [microsoftgraph/msgraph-training-java#14]
Hi
could you please let me know what is this error?
Caused by: com.microsoft.graph.core.ClientException: Error during http request

I'm using my personal microsoft account for uploading excel file on onedrive...! is this caused the problem?

**Comment by jasonjoh** [comment]
@hamedisu we're not set up to provide general Microsoft Graph support in the issues on samples here in GitHub. Since this is beyond the scope of this sample, I'm going to close this issue.

There's not enough information there to guess what your problem is. Typically if Graph returns a non-success HTTP status, there's an error payload in the body. Debugging this may uncover more details about the error.

**Comment by hamedisu** [comment]
Ok, thank you for your response.
as a last question...
Is it necessary to have a paid organization account on microsoft for uploading a file on onedrive automatically without any limit (for example 300 times on day)?
or I can use my personal free account without any limit? I use your tutorials for this goal last days without any problem, but today It doesn't work and I guess my account have been limited! 

thank you very much

**Comment by jasonjoh** [comment]
I'm not aware of any limitations put on Microsoft Graph with personal accounts that don't also apply to work/school accounts. Throttling information that is available is published at https://docs.microsoft.com/graph/throttling#service-specific-limits
