### ISSUE TITLE
How to adapt this to server-side or daemon application?

### ISSUE THREAD

**Issue by axk7812** [microsoftgraph/msgraph-training-java#16]
This uses the PublicClientApplication class

Following questions need to be answered:
1) how does the app registration process change? Can we use a client secret or do we need to use certificates? Where is this information found? 

2) Do we need to set the Redirect URI with daemon application?

3) What is the correct syntax for providing the scope string? I've seen everything online from "Mail.ReadWrite" to"https://graph.microsoft.com/.default"

4) How does this change if we use the ConfidentialClientApplication class?

**Comment by jasonjoh** [comment]
Thanks @axk7812 for your interest! We're not really setup to provide general support in GitHub issues that aren't directly related to the tutorial or sample itself. That being said, I'll give you the best information I can.

1. Microsoft identity platform has a ton of documentation on their available auth flows here: https://docs.microsoft.com/azure/active-directory/develop/v2-app-types. App registration is similar, but you'd need to add a secret OR certificate to use one of the server-side flows.
1. No, daemon's typically use [client credentials flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow), which doesn't require a redirect.
1. It depends on the flow and your approach to scopes. You can do them two ways: pre-define them by setting them explicitly on your app registration, or requesting them dynamically in your app. When you explicitly set them (which is required for a daemon app), you use the `https://graph.microsoft.com/.default` scope in your token request. When using dynamic (such as in this example), you specify each scope separated by a space in the requests. This allows you to do things like incremental consent: only ask for User.Read at login, then if the user decides to enable the mail features in your app, you can add the mail scopes etc.
4. `ConfidentialClientApplication` is required for server-side flows, since they need a secret or certificate. See https://docs.microsoft.com/azure/active-directory/develop/msal-client-applications
