### ISSUE TITLE
Authentication do not work

### ISSUE THREAD

**Issue by Moondancer83** [microsoftgraph/msgraph-training-java#3]
I have followed the tutorials instructions, however I get an authentication error all the time.

> AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

While I try the react version of the tutorial from [here](https://developer.microsoft.com/en-us/graph/get-started/react) it's working perfectly.
Both JavaScript and Java SDK versions are 1.7 (microsoft-graph) and 1.1 (msal).

**Comment by jasonjoh** [comment]
@Moondancer83 unfortunately the Microsoft Identity endpoints don't support the device code flow for personal Microsoft accounts, only for work/school accounts. See #1.

I thought I had added a note about this but I see that I did not. I'll get this into the tutorial.

**Comment by jasonjoh** [comment]
Well actually, it looks like they've added support for personal accounts! However, the app needs to be updated to support it.

- The app registration steps need to be changed so that you select **Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)** when registering.
- The `authority` string needs to be changed in Authentication.java:

    ```
    private final static String authority = "https://login.microsoftonline.com/common/";
    ```

**Comment by jasonjoh** [comment]
Did this resolve it for you?

**Comment by jasonjoh** [comment]
Closing due to no response.
